### PR TITLE
refactor(test) transfer behat to core module

### PR DESCRIPTION
**Pull request by wfajczyk**
# Description
Transfer behat to core module

Issue #737
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [ ] Behat Test

# Checklist:
- [x] I have read the contribution requirements and fulfill them.
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by wiewiurdp — DISMISSED** [review]

**Review by piotrkreft — COMMENTED** [review]
I think that the most common way to share some test base is to add Test namespace(not to confuse with Tests). So it'd be 'Ergonode/Core/Test' and potentially Behat subnamespace in it as is. What do You think?

**Review by piotrkreft — CHANGES_REQUESTED** [review]
It seems like core module is not dependant on behat package. Probably dependency should be added as a dev one with a suggestion perhaps?

**Comment by rprzedzik** [comment]
> I think that the most common way to share some test base is to add Test namespace(not to confuse with Tests). So it'd be 'Ergonode/Core/Test' and potentially Behat subnamespace in it as is. What do You think?

I think this is a good idea.
However, if it is not going to be confusing for developers ? 
Current test namespace is: `Ergonode/Core/Tests`

**Comment by piotrkreft** [comment]
> > I think that the most common way to share some test base is to add Test namespace(not to confuse with Tests). So it'd be 'Ergonode/Core/Test' and potentially Behat subnamespace in it as is. What do You think?
> 
> I think this is a good idea.
> However, if it is not going to be confusing for developers ?
> Current test namespace is: `Ergonode/Core/Tests`

It's not ideal of course(so I guess it could be confusing for some developers) but also it's not like I invented it. For an instance, this approach is used at Symfony. i.e: [Test](https://github.com/symfony/framework-bundle/tree/master/Test) vs [Tests](https://github.com/symfony/framework-bundle/tree/master/Tests). Symfony also does not include tests in the published version but that's another story. Additionally, if you'll look at the autoloading setup Test is autoloaded for all whereas Tests only for dev(so root).

**Review by wiewiurdp — DISMISSED** [review]

**Review by wiewiurdp — APPROVED** [review]

**Review by piotrkreft — APPROVED** [review]

**Pull request merged**
