### PR TITLE
bugfix(exporter-file, importer-ergonode-1) Handle escaping newlines on CSV export/import

### PR DESCRIPTION
**Pull request by kardi31**
# Description

Issue # 
https://github.com/ergonode/backend/issues/1460

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit Tests
- [ ] Behat Test

Functional tests on client implementation

# Checklist:
- [X] I have read the contribution requirements and fulfill them.
- [X] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by piotrkreft — CHANGES_REQUESTED** [review]
@kardi31 please setup 2 PR's
* for `release/1.0`
* for `master`

and add Changelog entry for 1.0.2

**Comment by kardi31** [comment]
@piotrkreft I added a PR to release/1.0 + updated this one with latest master due to failing tests.

**Comment by piotrkreft** [comment]
The changelog missing here as well

**Comment by kardi31** [comment]
I added changelog commit @piotrkreft

**Review by piotrkreft — APPROVED** [review]

**Review by rprzedzik — APPROVED** [review]

**Pull request merged**
